// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Haptic Braille",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Haptic Braille",
            targets: ["AppModule"],
            bundleIdentifier: "shah.ujval.me.Haptic-Braille",
            teamIdentifier: "GX2GUX7BH2",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .games
        )
    ],
    dependencies: [
        .package(url: "https://github.com/dkk/WrappingHStack", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "WrappingHStack", package: "wrappinghstack")
            ],
            path: ".",
            resources: [
                .process("App/Resources/AHAP")
            ]
        )
    ]
)
